In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [11]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    WITH sub AS(
        SELECT *,
            CASE 
                WHEN m.memid = 0 THEN f.guestcost * b.slots
                ELSE f.membercost * b.slots
            END AS cost       
        FROM Bookings AS b
        JOIN Facilities AS f
        ON b.facid = f.facid
        JOIN Members AS m
        ON b.memid = m.memid
    )
    SELECT name, SUM(cost) AS revenue 
    FROM sub
    HAVING revenue < 1000
    ORDER BY revenue DESC
    """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m1.surname || ', '|| m1.firstname AS recomended, m2.surname || ', '|| m2.firstname AS recomended
        FROM Members AS m1
        JOIN Members AS m2
        ON m1.recommendedby = m2.memid
        ORDER BY 1,2
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader, Florence', 'Stibbons, Ponder')
('Baker, Anne', 'Stibbons, Ponder')
('Baker, Timothy', 'Farrell, Jemima')
('Boothe, Tim', 'Rownam, Tim')
('Butters, Gerald', 'Smith, Darren')
('Coplin, Joan', 'Baker, Timothy')
('Crumpet, Erica', 'Smith, Tracy')
('Dare, Nancy', 'Joplette, Janice')
('Genting, Matthew', 'Butters, Gerald')
('Hunt, John', 'Purview, Millicent')
('Jones, David', 'Joplette, Janice')
('Jones, Douglas', 'Jones, David')
('Joplette, Janice', 'Smith, Darren')
('Mackenzie, Anna', 'Smith, Darren')
('Owen, Charles', 'Smith, Darren')
('Pinker, David', 'Farrell, Jemima')
('Purview, Millicent', 'Smith, Tracy')
('Rumney, Henrietta', 'Genting, Matthew')
('Sarwin, Ramnaresh', 'Bader, Florence')
('Smith, Jack', 'Smith, Darren')
('Stibbons, Ponder', 'Tracy, Burton')
('Worthington-Smyth, Henry', 'Smith, Tracy')

In [9]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
            ROUND(100.0 * SUM(slots)/
            (
                SELECT SUM (slots)
                FROM Bookings
                WHERE memid != 0
             ),2) AS percentage_of_usage_by_member
        FROM Bookings AS b
        LEFT JOIN Facilities AS f
        ON b.facid = f.facid
        WHERE memid != 0
        GROUP BY f.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 15.99)
('Massage Room 1', 13.02)
('Massage Room 2', 0.8)
('Pool Table', 12.6)
('Snooker Table', 12.66)
('Squash Court', 6.16)
('Table Tennis', 11.69)
('Tennis Court 1', 14.09)
('Tennis Court 2', 12.99)

In [10]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT strftime ('%m', b.starttime) AS month, f.name,
            ROUND(100.0 * SUM(slots)/
            (
                SELECT SUM (slots)
                FROM Bookings
                WHERE memid != 0
             ),2) AS percentage_of_usage_by_member
        FROM Bookings AS b
        LEFT JOIN Facilities AS f
        ON b.facid = f.facid
        WHERE memid != 0
        GROUP BY month, f.name
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 2.43)
('07', 'Massage Room 1', 2.44)
('07', 'Massage Room 2', 0.12)
('07', 'Pool Table', 1.62)
('07', 'Snooker Table', 2.06)
('07', 'Squash Court', 0.74)
('07', 'Table Tennis', 1.44)
('07', 'Tennis Court 1', 2.96)
('07', 'Tennis Court 2', 1.81)
('08', 'Badminton Court', 6.1)
('08', 'Massage Room 1', 4.65)
('08', 'Massage Room 2', 0.27)
('08', 'Pool Table', 4.46)
('08', 'Snooker Table', 4.65)
('08', 'Squash Court', 2.71)
('08', 'Table Tennis', 4.36)
('08', 'Tennis Court 1', 4.99)
('08', 'Tennis Court 2', 5.08)
('09', 'Badminton Court', 7.47)
('09', 'Massage Room 1', 5.92)
('09', 'Massage Room 2', 0.41)
('09', 'Pool Table', 6.52)
('09', 'Snooker Table', 5.95)
('09', 'Squash Court', 2.71)
('09', 'Table Tennis', 5.89)
('09', 'Tennis Court 1', 6.14)
('09', 'Tennis Court 2', 6.1)